variables:
  server_ip: 8.130.116.36
  jar_name: sentistrength-0.0.1-SNAPSHOT.jar
  upload_path: /home/SE3/sentiSpring
  password: 940926698xiAOL

stages:
  - build
  - upload
  - deploy

maven-build:
  stage: build
  image: registry.cn-hangzhou.aliyuncs.com/acs/maven
  script:
    - mvn clean
    - mvn package -Dmaven.test.skip=true
    - ls -l target/
  artifacts:
    paths:
      - target/$jar_name

upload-jar:
  stage: upload
  image: ictu/sshpass
  script:
    - ls -l
    - ls -l target/
    - sshpass -p $password scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no target/$jar_name root@$server_ip:$upload_path/$jar_name

deploy-job:
  stage: deploy
  image: ictu/sshpass
  script:
    - sshpass -p $password ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$server_ip "if [ -f $upload_path/run.pid ]; then kill \$(cat $upload_path/run.pid) && rm $upload_path/run.pid; fi|| exit 1"
    - sshpass -p $password ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$server_ip "nohup java -jar $upload_path/$jar_name >/dev/null 2>&1 & echo \$! > $upload_path/run.pid"
