spring:
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 50MB
      # 所有上传文件最大大小
      max-request-size: 50MB

server:
  port: 8082

files:
  upload:
    windowsPath: D:\sentiFiles\uploader\
    linuxPath: /home/sentiFiles/uploader/
  download:
    windowsPath: D:\sentiFiles\downloader\
    linuxPath: /home/sentiFiles/downloader/
  result:
    windowsPath: D:\sentiFiles\
    linuxPath: /home/sentiFiles/